// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementApp.Data
{
    public partial class Projects
    {
        public Projects()
        {
            Tasks = new HashSet<Tasks>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Title { get; set; } = null!;
        [Column(TypeName = "ntext")]
        public string Description { get; set; } = null!;
        [Column(TypeName = "datetime")]
        public DateTime? DateDue { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; } = null!;
        public int ProjectStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }

        [InverseProperty("Project")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}