// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementApp.Data
{
    public partial class Tasks
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Title { get; set; } = null!;
        public int TaskStatus { get; set; }
        public int ProjectId { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("Tasks")]
        public virtual Projects Project { get; set; } = null!;
    }
}